# Generated by Django 4.2.10 on 2024-05-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_newslettersubscription_delete_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
